set.seed(42)
output <- knitr::opts_knit$get("rmarkdown.pandoc.to")
if (!is.null(output) && output=="beamer") knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.path="figures/", fig.align='center')
knitr::opts_chunk$set(warning=FALSE, message=FALSE)
knitr::opts_knit$set(self.contained=FALSE)
knitr::opts_chunk$set(cache.path = "local/cache/")
library(pander)
panderOptions("table.style", "rmarkdown")
panderOptions("table.split.table", 120)
if(!file.exists("data/")) dir.create("data/")
if(!file.exists("figures/")) dir.create("figures/")
if(!file.exists("images/")) dir.create("images/")
library(ggplot2)
library(ggthemes)
library(plyr)
library(grid)
library(gridExtra)
theme_set(theme_bw())
